// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RainbowBraces
{
    internal sealed partial class Vsix
    {
        public const string Id = "RainbowBraces.1dff1bc5-a8e4-477b-9054-2b9ec6bb88d1";
        public const string Name = "Rainbow Braces";
        public const string Description = @"Colorizes matching brace pairs to make it easy to identify them and their scope. Works for curly brackets, parentheses, and square brackets.";
        public const string Language = "en-US";
        public const string Version = "1.0.500";
        public const string Author = "Mads Kristensen";
        public const string Tags = "braces, color";
    }
}
